
var ArticleAudioSourceController = AudioSourceController.createComponent("ArticleAudioSourceController");

ArticleAudioSourceController.createViewFragment = AudioSourceController.createViewFragment;
