
var ArticleVideoSourceController = VideoSourceController.createComponent("ArticleVideoSourceController");

ArticleVideoSourceController.createViewFragment = VideoSourceController.createViewFragment;
