
var ArticleImageSourceController = ImageSourceController.createComponent("ArticleImageSourceController");

ArticleImageSourceController.createViewFragment = ImageSourceController.createViewFragment;
