
var XHRProgressNotificationController = ProgressNotificationController.createComponent("XHRProgressNotificationController");

XHRProgressNotificationController.createViewFragment = ProgressNotificationController.createViewFragment;
