
var ExploreImageSourceController = ImageSourceController.createComponent("ExploreImageSourceController");

ExploreImageSourceController.createViewFragment = ImageSourceController.createViewFragment;
