
var ExploreVideoSourceController = VideoSourceController.createComponent("ExploreVideoSourceController");

ExploreVideoSourceController.createViewFragment = VideoSourceController.createViewFragment;
