
var ExploreAudioSourceController = AudioSourceController.createComponent("ExploreAudioSourceController");

ExploreAudioSourceController.createViewFragment = AudioSourceController.createViewFragment;
